

message("")
message("---------------------------------------------------------------------------------------------------")
message("THIS:              ${THIS}")
message("BUILD_TYPE:        ${BUILD_TYPE}")
message("INSTALL_PREFIX:    ${INSTALL_PREFIX}")
message("EXT_HEADER_PATH:   ${EXT_HEADER_PATH}")
message("EXT_BIN_PATH:      ${EXT_BIN_PATH}")
message("CMAKE_PATH:        ${CMAKE_PATH}")
message("RADICAL_PATH:      ${RADICAL_PATH}")
if(WIN32)
    message("MSVC SDK:          ${WINDOWS_SDK}")
endif()
message("---------------------------------------------------------------------------------------------------")
