function(RENDER)
    foreach(VALUE IN ITEMS ${ARGN})
        message(">> ${VALUE}") # can't use VAR
    endforeach()
endfunction(RENDER)

MACRO(SUBDIRLIST RESULT CUR_DIR)
    FILE(GLOB CHILDREN RELATIVE ${CUR_DIR} ${CUR_DIR}/*)
    FOREACH(CHILD ${CHILDREN})
        IF(IS_DIRECTORY "${CUR_DIR}/${CHILD}")
            SUBDIRLIST(${RESULT} "${CUR_DIR}/${CHILD}")
        ELSE()
            LIST(APPEND ${RESULT} "${CUR_DIR}/${CHILD}")
        ENDIF()
    ENDFOREACH()
ENDMACRO()


function(CONFIGURE_VISUAL_STUDIO_SOLUTION)
    foreach(SOURCE_FILE IN ITEMS ${ARGN})
        get_filename_component(SOURCE_PATH "${SOURCE_FILE}" PATH)
        string(REGEX REPLACE "${CMAKE_SOURCE_DIR}/Solution" "" RELATIVE_PATH "${SOURCE_PATH}")
        string(REPLACE "/" "\\\\" RELATIVE_PATH "${RELATIVE_PATH}")
        source_group("${RELATIVE_PATH}" FILES "${SOURCE_FILE}")
    endforeach()
    set_property(DIRECTORY ${CMAKE_CURRENT_SOURCE_DIR} PROPERTY VS_STARTUP_PROJECT ${THIS})
endfunction(CONFIGURE_VISUAL_STUDIO_SOLUTION)

function(CONFIGURE_VISUAL_STUDIO_STANDALONE_PROJECT)
    foreach(SOURCE_FILE IN ITEMS ${ARGN})
        get_filename_component(SOURCE_PATH "${SOURCE_FILE}" PATH)
        string(REGEX REPLACE "${CMAKE_SOURCE_DIR}/Project" "" RELATIVE_PATH "${SOURCE_PATH}")
        string(REPLACE "/" "\\\\" RELATIVE_PATH "${RELATIVE_PATH}")
        source_group("${RELATIVE_PATH}" FILES "${SOURCE_FILE}")
    endforeach()
    set_property(DIRECTORY ${CMAKE_CURRENT_SOURCE_DIR} PROPERTY VS_STARTUP_PROJECT ${THIS})
endfunction(CONFIGURE_VISUAL_STUDIO_STANDALONE_PROJECT)

function(CONFIGURE_VISUAL_STUDIO_PROJECT)
    foreach(SOURCE_FILE IN ITEMS ${ARGN})
        get_filename_component(SOURCE_PATH "${SOURCE_FILE}" PATH)
        string(REGEX REPLACE "${PROJECT_DIR}/${LIB}" "" RELATIVE_PATH "${SOURCE_PATH}")
        string(REPLACE "/" "\\\\" RELATIVE_PATH "${RELATIVE_PATH}")
        source_group("${RELATIVE_PATH}" FILES "${SOURCE_FILE}")
    endforeach()
endfunction(CONFIGURE_VISUAL_STUDIO_PROJECT)