function(SetStaticDependenciesOn Target)
    if(${BuildAll})
        foreach(LoLib ${StaticLibs})
            if(NOT "${Target}" STREQUAL "${LoLib}")
                add_dependencies(${Target} ${LoLib})
            endif()
        endforeach()
    endif()
endfunction()
