function(SetStaticDependenciesOn Target)
    if(${BuildAll})
        foreach(Lib ${StaticLibs})
            if(NOT "${Target}" STREQUAL "${Lib}")
                add_dependencies(${Target} ${Lib})
            endif()
        endforeach()
    endif()
endfunction()

