macro(PrintLibs)
    foreach(StaticLib ${StaticLibs})
        string(REPLACE "Radical::" "" StaticLib ${StaticLib})
        message("LIB >> ${StaticLib}")
    endforeach()
    set(FirstLibLoop ON)
endmacro()

function(LinkAllStaticLibs Target)
    foreach(LIB ${StaticLibs})
        message("LIB >> ${LIB}")
        LinkStatic(${Target} ${LIB})
    endforeach()
endfunction()

function(LinkStatic TARGET_FILE STATIC_LIB)
    target_link_libraries(${TARGET_FILE} PRIVATE ${STATIC_LIB})
endfunction()
