macro(PrintLibs)
    foreach(StaticLib ${StaticLibs})
        string(REPLACE "Radical::" "" StaticLib ${StaticLib})
        message("LIB >> ${StaticLib}")
    endforeach()
    set(FirstLibLoop ON)
endmacro()

function(LinkStatic TARGET_FILE STATIC_LIB)
    set(LocalInstalldir "${CMAKE_SOURCE_DIR}/Build/${OS_TYPE}/${BUILD_TYPE}/${BUILD_TYPE}")
    if(${BuildAll})
        if(${IsApp})
                target_link_libraries(${TARGET_FILE} ${LocalInstalldir}/lib/${PF}${STATIC_LIB}.${ST})
        else() # IsLib
                target_link_libraries(${TARGET_FILE} ${LocalInstalldir}/${PF}${STATIC_LIB}.${ST})
        endif()
    else()
        target_link_libraries(${TARGET_FILE} ${EXT_BIN_PATH}/lib/${PF}${STATIC_LIB}.${ST})
    endif()
endfunction()
