macro(PrintLibs)
    foreach(StaticLib ${StaticLibs})
        string(REPLACE "Radical::" "" StaticLib ${StaticLib})
        message("LIB >> ${StaticLib}")
    endforeach()
    set(FirstLibLoop ON)
endmacro()

function(LinkAllStaticLibs Target)
    foreach(LIB ${StaticLibs})
        message("LIB >> ${LIB}")
        LinkStatic(${Target} ${LIB})
    endforeach()
endfunction()

function(LinkStatic TARGET_FILE STATIC_LIB)
    set(LocalInstalldir "${CMAKE_SOURCE_DIR}/Build/${OS_TYPE}/${BUILD_TYPE}/${BUILD_TYPE}")
    if(${BuildAll})
        if(${IsApp})
                message(">>>> (APP Static Link) ${TARGET_FILE} << ${STATIC_LIB}")
                target_link_libraries(${TARGET_FILE} PRIVATE ${LocalInstalldir}/lib/${PF}${STATIC_LIB}.${ST})
        else() # IsLib
                message(">>>> (LIB Static Link) ${TARGET_FILE} << ${STATIC_LIB}")
                target_link_libraries(${TARGET_FILE} PRIVATE ${LocalInstalldir}/${PF}${STATIC_LIB}.${ST})
        endif()
    else()
        target_link_libraries(${TARGET_FILE} PRIVATE ${EXT_BIN_PATH}/lib/${PF}${STATIC_LIB}.${ST})
    endif()
endfunction()
